import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const griun = localFont({
  src: "./font/Griun＿Simsimche－Rg.ttf",
  display: "swap",
  variable: "--font-griun",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${griun.variable} antialiased`}>{children}</body>
    </html>
  );
}
